### ISSUE TITLE
Design question mailbox

### ISSUE THREAD

**Issue by patagoniahiker** [MassTransit/Sample-Booking#2]
Hello again, I am trying to extend this sample :100: with booking an event/room (resource), where -
1.  A customer/user creates a purchase/rent request
2.  A manager gets a notification in his inbox to approve
3.  Its then routed  (after approval) to _two_ places, a) specific person, and a b) a rolegroup

I've been reading, but I don't know these terms from your website, I see courier and slip, 
my question, can you please guide me, 
1.  what design/or which queue/transit design matches this inbox need well?
2.  how can messages be sent to a role?
3.  Is there a GUI that provides the admins a saga/queue management interface?

thanks

**Comment by phatboyg** [comment]
You might want to ask on the mailing list, as the issues of the samples are poorly moderated.

**Comment by patagoniahiker** [comment]
ok thanks
