### ISSUE TITLE
Publish a message in saga flow

### ISSUE THREAD

**Issue by simbanole** [MassTransit/Sample-Booking#4]
In the starbucks sample, I saw a message is published when payment is completed.
The code is like 
 When(PaymentComplete)
                        .Then((saga, message) =>
                        {
                            Console.WriteLine("Payment Complete for '{0}' got it!", saga.Name);
                            saga.ServeDrink();
                        })
                        .Complete()

  private void ServeDrink()
        {
            Console.WriteLine(string.Format("I've got a {0} ready for {1}!", Drink, Name));

            var message = new DrinkReadyMessage
            {
                CorrelationId = CorrelationId,
                Drink = Drink,
                Name = Name,
            };

            Bus.Publish(message);
        }

 The starbucks sample uses Masstransit 2.9, how can this be realized with MassTransit 3.5?

**Comment by phatboyg** [comment]
I'd suggest looking at a newer sample, one that is built on the new code.

Many are listed here: http://masstransit-project.com/MassTransit/learn/samples/

Also, there is a very complete sample with presentation at: https://github.com/phatboyg/Demo-Registration
